from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.utils import ImageReader
import io
import datetime
import os

def wrap_text(text, max_chars=55):
    """
    Robust scientific text wrapping for ReportLab PDF integration.
    """
    if not text:
        return []
    words = text.split(' ')
    lines = []
    current_line = []
    for word in words:
        if sum(len(w) for w in current_line) + len(current_line) + len(word) > max_chars:
            lines.append(' '.join(current_line))
            current_line = [word]
        else:
            current_line.append(word)
    if current_line:
        lines.append(' '.join(current_line))
    return lines

class PDFReportGenerator:
    def __init__(self):
        self.bri_blue = colors.HexColor("#00529C")
        self.risk_orange = colors.HexColor("#FF8C00")
        self.light_gray = colors.HexColor("#F7FAFC")
        self.border_gray = colors.HexColor("#E2E8F0")
        self.dark_text = colors.HexColor("#2D3748")

    def generate(self, data):
        """
        data: dictionary containing scientific report info
        """
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # 1. Header Design (Modern Geometric)
        p.setFillColor(self.bri_blue)
        p.rect(0, height - 1.25*inch, width, 1.25*inch, fill=1, stroke=0)
        
        # Diagonal Modern Shapes (White/Accent)
        p.setFillColor(colors.white)
        p.setStrokeColor(colors.white)
        p.setDash([])
        
        # Design shapes for top-right background effect
        p.saveState()
        p.setLineWidth(0.5)
        p.setStrokeColor(colors.white)
        p.setDash(4, 2)
        for i in range(10):
            p.line(width - 2.5*inch + i*5, height, width - 0.5*inch + i*5, height - 1.25*inch)
        
        # Draw a symbolic shield icon
        p.setDash([])
        p.setFillColor(colors.white)
        p.saveState()
        p.translate(width - 0.8*inch, height - 0.6*inch)
        p.scale(0.8, 0.8)
        shield = p.beginPath()
        shield.moveTo(0, 20)
        shield.curveTo(10, 20, 20, 15, 20, 0)
        shield.curveTo(20, -15, 0, -25, 0, -25)
        shield.curveTo(0, -25, -20, -15, -20, 0)
        shield.curveTo(-20, 15, -10, 20, 0, 20)
        p.drawPath(shield, fill=0, stroke=1)
        p.drawCentredString(0, -5, "SECURE")
        p.restoreState()
        p.restoreState()
        
        # Logo Bank
        logo_path = "logo_bank.png"
        logo_w = 0.8*inch
        if os.path.exists(logo_path):
            p.drawImage(logo_path, 0.4*inch, height - 0.85*inch, width=logo_w, preserveAspectRatio=True, mask='auto')
        
        # Header Titles
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 14)
        title_x = 1.35*inch
        p.drawString(title_x, height - 0.55*inch, "FRAUD DETECTION ANALYSIS SYSTEM (FDAS)")
        p.setFont("Helvetica", 8)
        p.drawString(title_x, height - 0.75*inch, "Enterprise Security Division - Cyber Intelligence & Digital Forensic")

        # Report ID Card
        card_w = 1.9*inch
        card_x = width - card_w - 0.4*inch
        p.setFillColor(colors.white)
        p.setStrokeColor(self.border_gray)
        p.roundRect(card_x, height - 1.0*inch, card_w, 0.45*inch, 4, fill=1, stroke=1)
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica", 7)
        p.drawString(card_x + 0.1*inch, height - 0.68*inch, "LAPORAN ID REFERENCE")
        p.setFont("Helvetica-Bold", 9)
        report_id = f"FDAS-{datetime.datetime.now().strftime('%Y%m%d')}-{data.get('account_id', 'UNK')[-4:]}"
        p.drawString(card_x + 0.1*inch, height - 0.85*inch, report_id)

        # 2. Main Title section
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica-Bold", 14)
        p.drawString(0.4*inch, height - 1.7*inch, "LAPORAN HASIL INVESTIGASI FRAUD TEKNO-BEHAVIORAL")
        p.setFont("Helvetica", 8)
        p.setFillColor(colors.grey)
        now_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        generated_by = data.get('generated_by', 'Unknown User')
        p.drawString(0.4*inch, height - 1.85*inch, f"Generated By: {generated_by}")
        p.drawString(0.4*inch, height - 2.0*inch, f"Timestamp: {now_str}")
        p.drawString(0.4*inch, height - 2.15*inch, f"Case Identifier: {data.get('account_id', 'Unknown')}")

        # SECTION I: Executive Summary
        curr_y = height - 2.5*inch
        p.setFillColor(self.bri_blue)
        p.roundRect(0.4*inch, curr_y + 0.1*inch, 0.2*inch, 0.2*inch, 2, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 10)
        p.drawCentredString(0.5*inch, curr_y + 0.15*inch, "I")
        p.setFillColor(self.bri_blue)
        p.drawString(0.7*inch, curr_y + 0.15*inch, "RINGKASAN EKSEKUTIF")
        p.setStrokeColor(self.bri_blue)
        p.setLineWidth(1)
        p.line(0.4*inch, curr_y, width - 0.4*inch, curr_y)

        # Dashboard Summary Mini Cards
        curr_y -= 0.8*inch
        # Account Card
        p.setFillColor(self.light_gray)
        p.setStrokeColor(self.border_gray)
        p.roundRect(0.4*inch, curr_y, 3.5*inch, 0.65*inch, 6, fill=1, stroke=1)
        p.setFillColor(self.bri_blue)
        p.circle(0.7*inch, curr_y + 0.32*inch, 0.2*inch, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 12)
        p.drawCentredString(0.7*inch, curr_y + 0.26*inch, "@")
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica", 8)
        p.drawString(1.0*inch, curr_y + 0.4*inch, "Account Identity (Masked)")
        p.setFont("Helvetica-Bold", 10)
        p.drawString(1.0*inch, curr_y + 0.2*inch, data.get('account_id', 'Unknown'))

        # Snapshot Card
        p.setFillColor(self.light_gray)
        p.roundRect(0.4*inch, curr_y - 0.8*inch, 3.5*inch, 0.65*inch, 6, fill=1, stroke=1)
        p.setFillColor(self.bri_blue)
        p.circle(0.7*inch, curr_y - 0.48*inch, 0.2*inch, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 12)
        p.drawCentredString(0.7*inch, curr_y - 0.54*inch, "#")
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica", 8)
        p.drawString(1.0*inch, curr_y - 0.4*inch, "Snapshot Data profiling")
        p.setFont("Helvetica-Bold", 10)
        p.drawString(1.0*inch, curr_y - 0.6*inch, f"{data.get('total_transactions', 0)} Transactions Analyzed")

        # Risk Indicator Visual (Right Big Card)
        status = data.get('status', 'NORMAL')
        risk_color = colors.red if status == "FRAUD" else colors.orange if status == "HIGH RISK" else colors.green
        p.setFillColor(self.bri_blue)
        p.roundRect(4.1*inch, curr_y - 0.8*inch, 3.7*inch, 1.45*inch, 10, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.setFont("Helvetica", 9)
        p.drawString(4.3*inch, curr_y + 0.4*inch, "TINGKAT RISIKO")
        p.setFont("Helvetica-Bold", 18)
        p.drawString(4.3*inch, curr_y + 0.1*inch, status)
        p.setFont("Helvetica", 8)
        
        if status == "FRAUD":
            p.drawString(4.3*inch, curr_y - 0.2*inch, "Analisis hybrid mendeteksi")
            p.drawString(4.3*inch, curr_y - 0.35*inch, "indikasi fraud kuat. Rekomendasi:")
            p.drawString(4.3*inch, curr_y - 0.5*inch, "Investigasi lanjutan oleh analis.")
        elif status == "HIGH RISK":
            p.drawString(4.3*inch, curr_y - 0.2*inch, "Analisis hybrid mendeteksi")
            p.drawString(4.3*inch, curr_y - 0.35*inch, "pola anomali menengah yang")
            p.drawString(4.3*inch, curr_y - 0.5*inch, "memerlukan review analis.")
        else:
            p.drawString(4.3*inch, curr_y - 0.2*inch, "Analisis hybrid menunjukkan")
            p.drawString(4.3*inch, curr_y - 0.35*inch, "pola transaksi normal.")
            p.drawString(4.3*inch, curr_y - 0.5*inch, "Monitoring rutin.")
        
        # Gauge Circle
        p.saveState()
        p.translate(7.1*inch, curr_y - 0.1*inch)
        p.setStrokeColor(colors.white)
        p.setLineWidth(6)
        p.circle(0, 0, 0.4*inch, fill=0, stroke=1)
        p.setStrokeColor(risk_color)
        p.setLineWidth(7)
        angle = 270 if status == "FRAUD" else 180 if status == "HIGH RISK" else 90
        p.arc(-0.4*inch, -0.4*inch, 0.4*inch, 0.4*inch, 90, -angle)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 8)
        p.drawCentredString(0, -0.05*inch, "RISK")
        p.restoreState()

        # SECTION II: Hybrid Scoring Metrics
        curr_y -= 1.3*inch
        p.setFillColor(self.bri_blue)
        p.roundRect(0.4*inch, curr_y + 0.1*inch, 0.2*inch, 0.2*inch, 2, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.drawCentredString(0.5*inch, curr_y + 0.15*inch, "II")
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica-Bold", 10)
        p.drawString(0.7*inch, curr_y + 0.15*inch, "METRIK SCORING HYBRID (BAB 3.8)")
        p.line(0.4*inch, curr_y, width - 0.4*inch, curr_y)

        curr_y -= 1.2*inch
        p.setFillColor(self.light_gray)
        p.roundRect(0.4*inch, curr_y, 7.45*inch, 1.1*inch, 6, fill=1, stroke=1)
        
        # Sub-scores
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica", 8)
        p.drawString(0.6*inch, curr_y + 0.85*inch, "1. Tabular Analysis (LightGBM)")
        p.setFont("Helvetica-Bold", 16)
        p.drawString(0.6*inch, curr_y + 0.6*inch, f"{data.get('lgbm_score', 0):.6f}")
        
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica", 8)
        p.drawString(0.6*inch, curr_y + 0.35*inch, "2. Temporal Sequence (LSTM)")
        p.setFont("Helvetica-Bold", 16)
        p.drawString(0.6*inch, curr_y + 0.1*inch, f"{data.get('lstm_score', 0):.6f}")
        
        # Vertical Separator
        p.setStrokeColor(self.border_gray)
        p.line(4.0*inch, curr_y + 0.1*inch, 4.0*inch, curr_y + 1.0*inch)
        
        # Fusion Score
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica-Bold", 10)
        p.drawString(4.3*inch, curr_y + 0.8*inch, "HYBRID FUSION SCORE (S-H)")
        p.setFillColor(self.risk_orange)
        p.setFont("Helvetica-Bold", 24)
        score_val = data.get('hybrid_score', 0)
        p.drawString(4.3*inch, curr_y + 0.45*inch, f"{score_val*100:.1f}%")
        
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica", 9)
        p.drawString(4.3*inch, curr_y + 0.2*inch, "CRITICALITY LEVEL:")
        p.setFillColor(self.risk_orange)
        p.setFont("Helvetica-Bold", 14)
        p.drawString(4.3*inch, curr_y + 0.02*inch, status)

        # Ensure we have behavior_exp for safe rendering
        behavior_exp = data.get('behavior_exp')
        if not behavior_exp:
            # Reconstruct fallback context
            behavior_exp = {
                'flags': {
                    'Abnormal Transaction Time': True,
                    'Transaction Velocity': False,
                    'Remark Anomaly': False,
                    'Destination Pattern Anomaly': False,
                    'Frequency Spike': True,
                    'Saldo Behavior': False
                },
                'triggered_indicators': ['Abnormal Transaction Time', 'Frequency Spike'],
                'explanation_score': score_val,
                'narrative_pdf': "Sistem mendeteksi deviasi korelasi temporal dan spike kuantitas transaksional. Kondisi ini menurunkan keandalan fungsional akun.",
                'confidence_level': "82.50%",
                'recommendations': [
                    "Monitoring intensif kanal transaksi frekuensi tinggi.",
                    "Lakukan pemanggilan outbound nasabah pelapor anomali.",
                    "Registrasi pada Internal Watchlist operasional."
                ]
            }

        # SECTION III: Advanced Explainable AI (XAI)
        curr_y -= 0.5*inch
        p.setFillColor(self.bri_blue)
        p.roundRect(0.4*inch, curr_y + 0.1*inch, 0.2*inch, 0.2*inch, 2, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.drawCentredString(0.5*inch, curr_y + 0.15*inch, "III")
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica-Bold", 10)
        p.drawString(0.7*inch, curr_y + 0.15*inch, "ANALISIS EXPLAINABLE AI (XAI)")
        p.setLineWidth(1)
        p.line(0.4*inch, curr_y, width - 0.4*inch, curr_y)

        # Advanced XAI Card layout with double-column visual analytics
        curr_y -= 1.65*inch
        p.setFillColor(self.light_gray)
        p.setStrokeColor(self.border_gray)
        p.roundRect(0.4*inch, curr_y, 7.45*inch, 1.55*inch, 6, fill=1, stroke=1)
        
        # Left Column: Faktor Dominan Risiko (all 6 indicators, ticked v / empty -)
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica-Bold", 8)
        p.drawString(0.6*inch, curr_y + 1.35*inch, "FAKTOR DOMINAN RISIKO & INDIKATOR")
        
        indicators_list = [
            ("Abnormal Time", "Abnormal Transaction Time"),
            ("Tx Velocity", "Transaction Velocity"),
            ("Remark Anomaly", "Remark Anomaly"),
            ("Destination Anomaly", "Destination Pattern Anomaly"),
            ("Frequency Spike", "Frequency Spike"),
            ("Saldo Anomaly", "Saldo Behavior")
        ]
        
        flags = behavior_exp.get('flags', {}) if isinstance(behavior_exp, dict) else {}
        for idx, (label, key) in enumerate(indicators_list):
            is_trig = flags.get(key, False)
            mark = "[v]" if is_trig else "[ ]"
            p.setFillColor(self.risk_orange if is_trig else colors.grey)
            p.setFont("Helvetica-Bold" if is_trig else "Helvetica", 7.5)
            col = idx // 3
            row_idx = idx % 3
            px = (0.6 + col*1.3)*inch
            py = curr_y + (1.05 - row_idx*0.28)*inch
            p.drawString(px, py, f"{mark} {label}")
            
        # Draw a Vertical Separator Line
        p.setStrokeColor(self.border_gray)
        p.setLineWidth(0.5)
        p.line(3.2*inch, curr_y + 0.1*inch, 3.2*inch, curr_y + 1.45*inch)
        
        # Right Column: Analisis XAI & Confidence
        p.setFillColor(self.dark_text)
        p.setFont("Helvetica-Bold", 8)
        p.drawString(3.4*inch, curr_y + 1.35*inch, "ANALISIS INTEGRAL EXPLAINABLE AI (XAI)")
        
        # Write Narrative PDF wrapped and formatted
        p.setFont("Helvetica-Oblique", 7.5)
        p.setFillColor(self.dark_text)
        narrative_txt = behavior_exp.get('narrative_pdf', '')
        narr_lines = wrap_text(narrative_txt, max_chars=62)
        for idx_line, line in enumerate(narr_lines[:6]):
            p.drawString(3.4*inch, curr_y + (1.12 - idx_line*0.16)*inch, line)
            
        # Draw Confidence Level
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica-Bold", 8)
        conf_lvl = behavior_exp.get('confidence_level', 'High Confidence') if isinstance(behavior_exp, dict) else 'High Confidence'
        p.drawString(3.4*inch, curr_y + 0.15*inch, f"Tingkat Confidence: {conf_lvl}")

        # SECTION IV: Recommendations
        curr_y -= 0.45*inch
        p.setFillColor(self.bri_blue)
        p.roundRect(0.4*inch, curr_y + 0.1*inch, 0.2*inch, 0.2*inch, 2, fill=1, stroke=0)
        p.setFillColor(colors.white)
        p.drawCentredString(0.5*inch, curr_y + 0.15*inch, "IV")
        p.setFillColor(self.bri_blue)
        p.setFont("Helvetica-Bold", 10)
        p.drawString(0.7*inch, curr_y + 0.15*inch, "REKOMENDASI OPERASIONAL INVESTIGASI")
        p.line(0.4*inch, curr_y, width - 0.4*inch, curr_y)

        curr_y -= 0.85*inch
        card_w = 2.38*inch
        
        if status == "FRAUD":
            titles = ["Investigation SOP", "Analyst Validation", "Forensic Review"]
        elif status == "HIGH RISK":
            titles = ["Enhanced Review", "Customer Verification", "Secondary Validation"]
        else:
            titles = ["Record Archives", "Historical Log", "Routine Monitoring"]

        recommendations_list = behavior_exp.get('recommendations', [])

        for i, title in enumerate(titles):
            px = 0.4*inch + i*(card_w + 0.15*inch)
            p.setFillColor(self.light_gray)
            p.setStrokeColor(self.border_gray)
            p.roundRect(px, curr_y, card_w, 0.75*inch, 6, fill=1, stroke=1)
            p.setFillColor(self.bri_blue)
            p.setFont("Helvetica-Bold", 9)
            p.drawString(px + 0.1*inch, curr_y + 0.55*inch, f"{i+1}. {title}")
            p.setFillColor(self.dark_text)
            p.setFont("Helvetica", 7.5)
            
            # Print the recommendation from our behavioral XAI model
            rec_text = recommendations_list[i] if i < len(recommendations_list) else ""
            rec_lines = wrap_text(rec_text, max_chars=34)
            for idx_line, line in enumerate(rec_lines[:2]):
                p.drawString(px + 0.1*inch, curr_y + (0.35 - idx_line*0.12)*inch, line)

        # Footer
        p.setFillColor(self.bri_blue)
        p.rect(0, 0, width, 0.65*inch, fill=1, stroke=0)
        p.setFillColor(colors.white)
        
        # Powered Created By Title with custom formatting
        p.setFont("Helvetica-Bold", 11)
        p.drawString(0.4*inch, 0.38*inch, "POWERED CREATED BY:")
        
        # Author Name
        p.setFont("Helvetica", 10)
        p.drawString(0.4*inch, 0.20*inch, "Rafif Ramadhan Al Yarda")
        
        # Security & Forensics Division Line on the right side
        p.setFont("Helvetica", 8)
        p.drawRightString(width - 0.4*inch, 0.28*inch, "Enterprise Security Division - Digital Risk & Fraud Forensics Department")

        p.showPage()
        p.save()
        
        pdf = buffer.getvalue()
        buffer.close()
        return pdf

def generate_pdf_report(data):
    """Generates PDF report using PDFReportGenerator instance."""
    generator = PDFReportGenerator()
    return generator.generate(data)
